name: motislib CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-motislib:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/motis-project/docker-cpp-build
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake (Linux)
        run: cmake -G Ninja -S . -B build -DBUILD_EXECUTABLE=OFF

      - name: Build motislib (Linux)
        run: cmake --build build --target motislib

  macos-motislib:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure CMake (macOS)
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_EXECUTABLE=OFF

      - name: Build motislib (macOS)
        run: cmake --build build --config Release --target motislib

  windows-motislib:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake (Windows)
        run: >-
          cmake -G Ninja -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_EXECUTABLE=OFF

      - name: Build motislib (Windows)
        run: cmake --build build --config Release --target motislib
